version: "3.8"
services:
  mongo:
    image: mongo:6.0
    container_name: catalog-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - catalog-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: catalog-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - catalog-network

  catalog-service:
    build:
      context: ./services/catalog
    container_name: catalog-service
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/catalog
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - PROMETHEUS_ENDPOINT=http://prometheus:9090
      - JAEGER_AGENT_HOST=jaeger-agent
      - ELASTICSEARCH_URL=http://localhost:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=topsecret
    depends_on:
      - mongo
      - elasticsearch
      - rabbitmq
      - prometheus
      - jaeger
    networks:
      - catalog-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - catalog-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - catalog-network

  jaeger-agent:
    image: jaegertracing/jaeger-agent:latest
    container_name: jaeger-agent
    ports:
      - "5775:5775/udp"
      - "14250:14250"
    networks:
      - catalog-network

  jaeger-collector:
    image: jaegertracing/jaeger-collector:latest
    container_name: jaeger-collector
    ports:
      - "14267:14267"
      - "14268:14268"
    networks:
      - catalog-network

  jaeger-query:
    image: jaegertracing/jaeger-query:latest
    container_name: jaeger-query
    ports:
      - "16686:16686"
    depends_on:
      - jaeger-collector
    networks:
      - catalog-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=topsecret
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=topsecret
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  esdata:
  mongo-data:

networks:
  catalog-network:
    driver: bridge
