apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: catalog-mongodb
spec:
    serviceName: "catalog-mongodb"
    replicas: 1
    selector:
        matchLabels:
            app: catalog-mongodb
    template:
        metadata:
            labels:
                app: catalog-mongodb
        spec:
            containers:
                - name: mongodb
                  image: mongo:4.4
                  ports:
                      - containerPort: 27017
                  volumeMounts:
                      - name: mongodb-persistent-storage
                        mountPath: /data/db
    volumeClaimTemplates:
        - metadata:
              name: mongodb-persistent-storage
          spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                  requests:
                      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
    name: catalog-mongodb
spec:
    ports:
        - port: 27017
          targetPort: 27017
    selector:
        app: catalog-mongodb
