apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: boilerplate-mongodb
spec:
  serviceName: "boilerplate-mongodb"
  replicas: 1
  selector:
    matchLabels:
      app: boilerplate-mongodb
  template:
    metadata:
      labels:
        app: boilerplate-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-persistent-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: boilerplate-mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: boilerplate-mongodb
