apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: boilerplate-postgres
spec:
  serviceName: "boilerplate-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: boilerplate-postgres
  template:
    metadata:
      labels:
        app: boilerplate-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: boilerplate-postgres-secret
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: boilerplate-postgres-secret
                  key: password
            - name: POSTGRES_DB
              value: "mydb"
          volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: boilerplate-postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: boilerplate-postgres
