apiVersion: apps/v1
kind: Deployment
metadata:
  name: boilerplate-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boilerplate-redis
  template:
    metadata:
      labels:
        app: boilerplate-redis
    spec:
      containers:
        - name: redis
          image: redis:6
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: boilerplate-redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: boilerplate-redis
